### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by LazyAndBeyond** [lgaticaq/anime-dl#36]
Uncaught We had a promise error 
TypeError: Cannot read property '1' of null
    at Object.<anonymous> (/app/node_modules/anime-dl/src/index.js:167:18)
    at /app/node_modules/cheerio/lib/api/traversing.js:306:18
    at /app/node_modules/lodash/_baseReduce.js:18:9
    at /app/node_modules/lodash/_createBaseEach.js:24:11
    at baseReduce (/app/node_modules/lodash/_baseReduce.js:15:3)
    at Object.reduce (/app/node_modules/lodash/reduce.js:48:10)
    at initialize.exports.map (/app/node_modules/cheerio/lib/api/traversing.js:305:23)
    at IncomingMessage.res.on.err (/app/node_modules/anime-dl/src/index.js:163:14)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

**Comment by lgaticaq** [comment]
What was the search you did?

**Comment by LazyAndBeyond** [comment]
i tryed one piece and naruto

**Comment by lgaticaq** [comment]
Paste your code please
